spring.application.name=security
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/LinkedIn?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=lpoonam123!!!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=abhishek
spring.security.user.password={noop}abhi123

//redis
spring.data.redis.host=localhost
spring.data.redis.port=6379